[project]
name = "Quantum_Racing"
hackathon = "solana_riptide"
priority = "CRITICAL"

[build]
command = "pip install -r requirements.txt && python quantum_fix.py"
quantum_boost = true

[deploy]
target = "replit"
resource_level = "quantum"

[blockchain]
avalanche_subnet = "Yt9d8RRW9JcoqfvyefqJJMX14HawtBc28J9CQspQKPkdonp1y"
solana_integration = true
